name: notes_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: 2.0.0+3
  path_provider: 2.0.1
  intl: 0.17.0
  flutter_staggered_grid_view: 0.4.0
  flutter_speed_dial: ^4.2.0
  image_picker: ^0.8.4
  image_cropper: ^1.4.1
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.1
  change_app_package_name: ^0.1.3
  flutter_test:
    sdk: flutter
  


# flutter_native_splash:
#   color: "#FFFFFF"
#   image: assets/splash2.png
#   android: true
#   ios: true

flutter_native_splash:
  color: "#263238"
  image: assets/splash.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/myicon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/myicon.png
  - assets/1 (1).png
  - assets/1 (2).png
  - assets/1 (3).png

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
  
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    
    - family: Myicons
      fonts:
        - asset: assets/fonts/Myicons.ttf

